const PIX_KEY = "21 971963818";
const SCRIPT_URL = "https://script.google.com/macros/s/AKfycbx68kIYLxZsN0eDyZfkCSLnRwEHjhArsEjKXdUyFrIJ2IAOIspf94n2jkqST2FOhZk19g/exec";

const valoresProdutos = {
  "Micro-ondas": 100, "Fogão": 100, "Armário de cozinha": 100, "Geladeira": 100,
  "Painel para TV": 100, "Sofá": 100, "Televisão": 100, "Ar-condicionado": 100,
  "Armário": 100, "Colchão de casa D20": 100, "Sapateira": 100, "Máquina de lavar": 100,
  "Aspirador de pó": 100, "Sanduicheira": 100, "Liquidificador": 170, "Mixer": 170,
  "Jogo de canecas": 75, "Jogo de pratos de porcelanato": 100, "Utensílios de silicone":50,
  "Boleira de vidro":50, "Garrafa térmica":55, "Escorredor de louça de parede":60,
  "Escorredores de inox":70, "Talheres":60, "Potes herméticos J1":90, "Potes herméticos J2":105,
  "Jogo de copos de vidro":65, "Jogo de tabuleiros":85, "Jogo de pirex":100, "Ralador":50,
  "Tábua de inox":50, "Lixeiras":55, "Suporte para papel higiênico":55, "Kits suporte de toalha":75,
  "Espelho":80, "Toalhas de banho":100, "Toalhas de rosto":50, "Kit porta algodão, escova e cotonete + saboneteira":70,
  "Cortina":100, "Tapete":70, "Capa de almofada":90, "Edredom":120, "2 jogos de lençol":70,
  "Travesseiros":75, "Cabeceira":60, "Capa de colchão impermeável":50, "Sexto de roupa":50,
  "Mope":50, "Ferro de passar roupa":110, "Tábua de passar roupa":100, "Varal de teto":65,
  "Varal de chão":90, "Panela de pressão":150, "Jogo de panelas":100
};

// URLs das imagens
const imagensProdutos = {
  "Micro-ondas": "imagens/MICROONDAS.jpg",
  "Fogão": "imagens/FOGAO.jpg",
  "Armário de cozinha": "imagens/ARMARIODECOZINHA.jpg",
  "Geladeira": "imagens/GELADEIRA.jpg",
  "Painel para TV": "imagens/PAINELPARATV.jpg",
  "Sofá": "imagens/SOFA.jpg",
  "Televisão": "imagens/TELEVISÃO.jpg",
  "Ar-condicionado": "imagens/ARCONDICIONADO.jpg",
  "Armário": "imagens/ARMARIO.jpg",
  "Colchão de casa D20": "imagens/COLCHAO.jpg",
  "Sapateira": "imagens/SAPATEIRA.jpg",
  "Máquina de lavar": "imagens/MAQUINADELAVAR.jpeg",
  "Aspirador de pó": "imagens/ASPIRADORDEPO.jpg",
  "Sanduicheira": "imagens/SANDUICHEIRA.jpg",
  "Liquidificador": "imagens/LIQUIDIFICADOR.jpg",
  "Mixer": "imagens/MIXER.jpg",
  "Jogo de canecas": "imagens/JOGODECANECAS.jpg",
  "Jogo de pratos de porcelanato": "imagens/JOGODEPRATOSPORCELANADO.jpg",
  "Utensílios de silicone": "imagens/UTENCILIOSDESILICONE.jpg",
  "Boleira de vidro": "imagens/BOLEIRADEVIDRO.jpg",
  "Garrafa térmica": "imagens/GARRAFATERMICA.jpg",
  "Escorredor de louça de parede": "imagens/ESCORREDORDELOUÇADEPARADE.jpg",
  "Escorredores de inox": "imagens/ESCORREDORDEINOX.jpeg",
  "Talheres": "imagens/TALHERES.jpg",
  "Potes herméticos J1": "imagens/POTESHERMETICOSJ1.jpg",
  "Potes herméticos J2": "imagens/POTESHERMETICOSJ2.jpg",
  "Jogo de copos de vidro": "imagens/JOGODECOPOSDEVIDRO.jpg",
  "Jogo de tabuleiros": "imagens/JOGODETABULEIROS.jpg",
  "Jogo de pirex": "imagens/JOGODEPIREX.jpg",
  "Ralador": "imagens/RALADOR.jpg",
  "Tábua de inox": "imagens/TABUADEINOX.jpg",
  "Lixeiras": "imagens/LIXEIRA.jpeg",
  "Suporte para papel higiênico": "imagens/SUPORTEHIGIENICO.jpeg",
  "Kits suporte de toalha": "imagens/KITSUPORTEDETOALHA.jpg",
  "Espelho": "imagens/ESPELHO.jpg",
  "Toalhas de banho": "imagens/TOALHASDEBANHO.jpg",
  "Toalhas de rosto": "imagens/TOALHASDEROSTO.jpg",
  "Kit porta algodão, escova e cotonete + saboneteira": "imagens/KITALGODAOESCOVA.jpg",
  "Cortina": "imagens/CORTINA.jpg",
  "Tapete": "imagens/TAPETE.jpg",
  "Capa de almofada": "imagens/CAPADEALMOFADA.jpg",
  "Edredom": "imagens/EDREDOM.jpg",
  "2 jogos de lençol": "imagens/JOGODELENCOL.jpg",
  "Travesseiros": "imagens/TRAVESSEIRO.jpeg",
  "Cabeceira": "imagens/CABECEIRA.jpg",
  "Capa de colchão impermeável": "imagens/CAPADECOLCHAOIMPERMEAVEL.jpg",
  "Sexto de roupa": "imagens/SEXTODEROUPA.jpg",
  "Mope": "imagens/MOPE.jpg",
  "Ferro de passar roupa": "imagens/FERRODEPASSAR.jpg",
  "Tábua de passar roupa": "imagens/TABUADEPASSAR.jpg",
  "Varal de teto": "imagens/VARALTETO.jpg",
  "Varal de chão": "imagens/VARALCHAO.jpg",
  "Panela de pressão": "imagens/PANELADEPRESSAO.jpg",
  "Jogo de panelas": "imagens/JOGODEPANELA.jpg"
};

// O resto do código mantém igual (criarCards, criarCard, abrirConfirm, confirmarCompra...) 
// Você pode copiar exatamente o código do script.js que te enviei antes e apenas substituir o objeto "imagensProdutos" por este completo.
